/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 5.4.0-6ubuntu1~16.04.4 -O2 -fstack-protector-strong -fPIC -Os) */

module relu(clk, rst, g_input, e_input, o);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  input clk;
  input [7:0] e_input;
  input [7:0] g_input;
  output [7:0] o;
  input rst;
  XOR _32_ (
    .A(e_input[0]),
    .B(g_input[0]),
    .Z(o[0])
  );
  IV _33_ (
    .A(g_input[2]),
    .Z(_00_)
  );
  AND _34_ (
    .A(e_input[0]),
    .B(g_input[0]),
    .Z(_01_)
  );
  XOR _35_ (
    .A(_01_),
    .B(g_input[1]),
    .Z(_02_)
  );
  XOR _36_ (
    .A(_01_),
    .B(e_input[1]),
    .Z(_03_)
  );
  NAND _37_ (
    .A(_03_),
    .B(_02_),
    .Z(_04_)
  );
  XOR _38_ (
    .A(_04_),
    .B(_01_),
    .Z(_05_)
  );
  XOR _39_ (
    .A(_05_),
    .B(_00_),
    .Z(_06_)
  );
  XOR _40_ (
    .A(_06_),
    .B(e_input[2]),
    .Z(o[2])
  );
  IV _41_ (
    .A(g_input[4]),
    .Z(_07_)
  );
  XOR _42_ (
    .A(_05_),
    .B(e_input[2]),
    .Z(_08_)
  );
  ANDN _43_ (
    .A(_06_),
    .B(_08_),
    .Z(_09_)
  );
  XOR _44_ (
    .A(_09_),
    .B(_05_),
    .Z(_10_)
  );
  IV _45_ (
    .A(g_input[3]),
    .Z(_11_)
  );
  XOR _46_ (
    .A(_10_),
    .B(_11_),
    .Z(_12_)
  );
  XOR _47_ (
    .A(_10_),
    .B(e_input[3]),
    .Z(_13_)
  );
  ANDN _48_ (
    .A(_12_),
    .B(_13_),
    .Z(_14_)
  );
  XOR _49_ (
    .A(_14_),
    .B(_10_),
    .Z(_15_)
  );
  XOR _50_ (
    .A(_15_),
    .B(_07_),
    .Z(_16_)
  );
  XOR _51_ (
    .A(_16_),
    .B(e_input[4]),
    .Z(o[4])
  );
  XOR _52_ (
    .A(_02_),
    .B(e_input[1]),
    .Z(o[1])
  );
  XOR _53_ (
    .A(_12_),
    .B(e_input[3]),
    .Z(o[3])
  );
  IV _54_ (
    .A(g_input[5]),
    .Z(_17_)
  );
  XOR _55_ (
    .A(_15_),
    .B(e_input[4]),
    .Z(_18_)
  );
  ANDN _56_ (
    .A(_16_),
    .B(_18_),
    .Z(_19_)
  );
  XOR _57_ (
    .A(_19_),
    .B(_15_),
    .Z(_20_)
  );
  XOR _58_ (
    .A(_20_),
    .B(_17_),
    .Z(_21_)
  );
  XOR _59_ (
    .A(_21_),
    .B(e_input[5]),
    .Z(o[5])
  );
  IV _60_ (
    .A(e_input[7]),
    .Z(_22_)
  );
  XOR _61_ (
    .A(_20_),
    .B(e_input[5]),
    .Z(_23_)
  );
  ANDN _62_ (
    .A(_21_),
    .B(_23_),
    .Z(_24_)
  );
  XOR _63_ (
    .A(_24_),
    .B(_20_),
    .Z(_25_)
  );
  IV _64_ (
    .A(g_input[6]),
    .Z(_26_)
  );
  XOR _65_ (
    .A(_25_),
    .B(_26_),
    .Z(_27_)
  );
  XOR _66_ (
    .A(_25_),
    .B(e_input[6]),
    .Z(_28_)
  );
  ANDN _67_ (
    .A(_27_),
    .B(_28_),
    .Z(_29_)
  );
  XOR _68_ (
    .A(_29_),
    .B(_25_),
    .Z(_30_)
  );
  XOR _69_ (
    .A(_30_),
    .B(g_input[7]),
    .Z(_31_)
  );
  XOR _70_ (
    .A(_31_),
    .B(_22_),
    .Z(o[7])
  );
  XOR _71_ (
    .A(_27_),
    .B(e_input[6]),
    .Z(o[6])
  );
endmodule
